# Generated by Django 5.1.6 on 2025-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gallery_gallerycategory_delete_contact_delete_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
