# Generated by Django 5.1.6 on 2025-07-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_blogpost_image_blogimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
    ]
