# Generated by Django 5.1.6 on 2025-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_blogpost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='background_image',
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
